@PlayingWithHttpClient_HostAddress = http://localhost:5067

@Secure_HostAddress = https://localhost:7100

GET {{PlayingWithHttpClient_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Secure_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Secure_HostAddress}}/api/github/users/v1/kriss3
Accept: application/json

###
GET {{Secure_HostAddress}}/api/github/users/v2/kriss3
Accept: application/json

###
GET {{Secure_HostAddress}}/api/github/users/v3/kriss3
Accept: application/json

###
GET {{Secure_HostAddress}}/api/github/users/v4/kriss3
Accept: application/json