<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="System.Buffers" Version="4.6.0" />
    <PackageVersion Include="System.Memory" Version="4.6.0" />
    <PackageVersion Include="System.Numerics.Vectors" Version="4.6.0" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
    <PackageVersion Include="System.Text.Encodings.Web" Version="9.0.0" />
    <PackageVersion Include="System.Text.Json" Version="9.0.0" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
    <PackageVersion Include="System.ValueTuple" Version="4.5.0" />
    <PackageVersion Include="RestSharp" Version="112.1.0" />
    <PackageVersion Include="Serilog" Version="4.0.2" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.2" />
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
	<PackageVersion Include="System.Data.DataSetExtensions" Version="4.5.0" />
	<PackageVersion Include="Cova.Functional" Version="4.5.0" />
	<PackageVersion Include="Cova.ServiceErrors" Version="4.5.0" />
	<PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />

    
  </ItemGroup>
</Project>