<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Cova.Functional" />
    <PackageReference Include="Cova.ServiceErrors" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\DomainLayer\" />
    <Folder Include="src\ApplicationLayer\" />
    <Folder Include="src\ApiLayer\" />
  </ItemGroup>

</Project>
